[package]
name = "my-grep"
version = "0.1.0"
authors = ["wasuken <wevorence@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.1"
glob = "0.3.0"
